import type { MenuCategory } from './types'

export const MENU: MenuCategory[] = [
  {
    id: 'signature',
    label: 'Signature',
    items: [
      {
        id: 'spanish-seasalt-latte',
        name: 'Spanish Seasalt Latte',
        subtitle: 'Espresso · Milk · Condensed Milk · Sea Salt Cream',
        priceHot: 140,
        priceIce: 150,
        priceFixed: null,
      },
      {
        id: 'white-mocha-americano',
        name: 'White Mocha Americano',
        subtitle: 'Espresso · White Chocolate Sauce · Breve',
        priceHot: 130,
        priceIce: 140,
        priceFixed: null,
      },
      {
        id: 'cereal-cream-latte',
        name: 'Cereal Cream Latte',
        subtitle: 'Espresso · Milk · Cereal · Sea Salt Cream',
        priceHot: 160,
        priceIce: 170,
        priceFixed: null,
      },
      {
        id: 'amber-cream-latte',
        name: 'Amber Cream Latte',
        subtitle: 'Espresso · Condensed Milk · Caramel · Milk · Sea Salt Cream',
        priceHot: 140,
        priceIce: 150,
        priceFixed: null,
      },
    ],
  },
  {
    id: 'espresso',
    label: 'Espresso',
    items: [
      {
        id: 'americano',
        name: 'Americano',
        subtitle: 'Espresso · Water',
        priceHot: 100,
        priceIce: 100,
        priceFixed: null,
      },
      {
        id: 'cafe-latte',
        name: 'Cafe Latte',
        subtitle: 'Espresso · Milk',
        priceHot: 110,
        priceIce: 120,
        priceFixed: null,
      },
      {
        id: 'spanish-latte',
        name: 'Spanish Latte',
        subtitle: 'Espresso · Condensed Milk · Milk',
        priceHot: 120,
        priceIce: 130,
        priceFixed: null,
      },
      {
        id: 'mocha-latte',
        name: 'Mocha Latte',
        subtitle: 'Espresso · Chocolate Sauce · Milk',
        priceHot: 130,
        priceIce: 140,
        priceFixed: null,
      },
      {
        id: 'caramel-macchiato',
        name: 'Caramel Macchiato',
        subtitle: 'Espresso · Caramel · Vanilla Syrup · Milk',
        priceHot: 130,
        priceIce: 140,
        priceFixed: null,
      },
      {
        id: 'white-chocolate-mocha',
        name: 'White Chocolate Mocha',
        subtitle: 'Espresso · White Chocolate Sauce · Milk',
        priceHot: 130,
        priceIce: 140,
        priceFixed: null,
      },
    ],
  },
  {
    id: 'non-coffee',
    label: 'Non-Coffee',
    items: [
      {
        id: 'matcha-latte',
        name: 'Matcha Latte',
        subtitle: 'Ceremonial Matcha · Milk',
        priceHot: 160,
        priceIce: 170,
        priceFixed: null,
      },
      {
        id: 'matcha-seasalt-latte',
        name: 'Matcha Seasalt Latte',
        subtitle: 'Ceremonial Matcha · Milk · Seasalt Cream',
        priceHot: 180,
        priceIce: 190,
        priceFixed: null,
      },
      {
        id: 'chocolate-milk',
        name: 'Chocolate Milk',
        subtitle: 'Chocolate Sauce · Milk',
        priceHot: 110,
        priceIce: 120,
        priceFixed: null,
      },
      {
        id: 'strawberry-milk',
        name: 'Strawberry Milk',
        subtitle: 'Strawberry Jam · Milk',
        priceHot: null,
        priceIce: 120,
        priceFixed: null,
      },
    ],
  },
  {
    id: 'meal',
    label: 'Meal',
    items: [
      {
        id: 'hungarian-sausage-meal',
        name: 'Hungarian Sausage Meal',
        subtitle: 'Hungarian sausage served with rice',
        priceHot: null,
        priceIce: null,
        priceFixed: 150,
      },
      {
        id: 'bacon-and-egg-meal',
        name: 'Bacon and Egg Meal',
        subtitle: 'Crispy bacon and egg served with rice',
        priceHot: null,
        priceIce: null,
        priceFixed: 150,
      },
      {
        id: 'pesto-tuna-fusilli',
        name: 'Pesto Tuna Fusilli',
        subtitle: 'Fusilli, basil pesto, flavorful tuna',
        priceHot: null,
        priceIce: null,
        priceFixed: 160,
      },
    ],
  },
  {
    id: 'waffle',
    label: 'Waffle',
    items: [
      {
        id: 'nutella-waffle',
        name: 'Nutella Waffle',
        subtitle: 'Golden waffle, Nutella, sweet toppings',
        priceHot: null,
        priceIce: null,
        priceFixed: 120,
      },
      {
        id: 'cream-cheese-waffle',
        name: 'Cream Cheese Waffle',
        subtitle: 'Golden waffle, cream cheese',
        priceHot: null,
        priceIce: null,
        priceFixed: 120,
      },
    ],
  },
  {
    id: 'snack',
    label: 'Snack',
    items: [
      {
        id: 'cheesy-beef-nachos',
        name: 'Cheesy Beef Nachos',
        subtitle: 'Crispy tortilla chips, seasoned beef, melted cheese',
        priceHot: null,
        priceIce: null,
        priceFixed: 180,
      },
    ],
  },
]
